<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ECR</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-03-29T23:28:13</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>afe5b466-4728-4f6b-bea3-3a7ee0d29e74</testSuiteGuid>
   <testCaseLink>
      <guid>b2477d01-eb86-40c0-804a-02efd4ee3cba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ECR/TestCases/ECR_Create_Approve_DataDriven</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>cfae3ab7-7798-41a9-976d-eb5d30f2dded</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/ECR/ECRTestData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>cfae3ab7-7798-41a9-976d-eb5d30f2dded</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>RD</value>
         <variableId>7effb63f-ef8e-4652-ae92-39f42427663f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cfae3ab7-7798-41a9-976d-eb5d30f2dded</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>RL</value>
         <variableId>4f59635a-de8a-4fdc-a7b3-5b6ecd2f252f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cfae3ab7-7798-41a9-976d-eb5d30f2dded</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PL</value>
         <variableId>230185c4-88bd-4126-b537-0b213bf9b04c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cfae3ab7-7798-41a9-976d-eb5d30f2dded</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Org</value>
         <variableId>3801346c-58b1-4223-9002-25e4a2bbd2e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cfae3ab7-7798-41a9-976d-eb5d30f2dded</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Acc</value>
         <variableId>a45e8509-3ac5-4ec9-9b1e-cc2f60fc4d70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7da9827f-88df-4025-b3df-d26043eabfda</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cfae3ab7-7798-41a9-976d-eb5d30f2dded</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PLTL</value>
         <variableId>abb47d0d-6395-4a35-b00c-cb5765af9a8b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d42d66a6-0277-418d-b592-cbb0dc76d611</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cfae3ab7-7798-41a9-976d-eb5d30f2dded</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseNo</value>
         <variableId>75039f21-0b19-4bda-a6ee-92c71cc9cadb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cfae3ab7-7798-41a9-976d-eb5d30f2dded</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Filepath</value>
         <variableId>7116096b-1927-49d4-96ba-8c2c70c4c96b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cfae3ab7-7798-41a9-976d-eb5d30f2dded</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>RDD</value>
         <variableId>98765ec8-6aad-43d8-ac53-f52ee17b3b0b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cfae3ab7-7798-41a9-976d-eb5d30f2dded</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CLINIC</value>
         <variableId>d4cc0c83-33ed-49ec-bb0f-6c9cfd721448</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cfae3ab7-7798-41a9-976d-eb5d30f2dded</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>OPS</value>
         <variableId>61a80624-1784-4bab-a68b-fb2970ee7fc9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c3c7f8c3-9349-41c4-bc67-df2ea2556413</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ECR/TestCases/TC_ECR_Create_Approve</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f243e616-6566-43cc-9994-b0b01d48b69b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d5a30d2-2bd5-4e74-abe1-26b9ecf6a874</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b97825f-3273-47f0-a571-0c5a8719575a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>efbdd58b-fc17-498e-b129-df6aba5d9ffc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86236e9c-8f2c-4432-b4f8-8468287be344</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f7d795f-b934-48b5-9725-a41b68926c6e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ebf6a25-fefe-4d0d-bfe4-0d05cde14907</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ecfee14-e04c-468d-9dbc-adb18b9735b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f2c6232-9eda-49a9-94ea-067356efe67e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47172a18-e956-4f38-b501-3ce500b28466</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b05d6258-4469-44e0-b959-7d03cb6abc11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>556b0cf2-fe16-492e-8858-aff0a6e18a5f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c4b5ccd-f597-49fe-bb23-e3b1e03bb17b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec0e1a52-df0d-4381-a447-3357e60556c4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>44f2dafc-91b4-4799-9600-debfee9fb610</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ECR/TestCases/TC_ECR_Create_Reject</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40e97db8-2cd0-43f8-95b9-591cfda4f51b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c23377e-7b2f-4f61-89df-264c19faaa08</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d92676fb-cc77-4a90-b7c2-a9d52935e2c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f61da936-8a8d-4476-a462-ba16952e3888</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88f74331-3b36-415b-a7dd-855ecfba3816</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce41af42-dfaf-41a8-b39e-316b2d62b8bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6381f797-df86-4675-baa8-1a2b3176482c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98381512-42a7-4a13-b57f-0d7c68aed3c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16379680-9c26-4fa2-bec3-392b93fb0913</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07103eed-c4d6-4095-b6d0-ed7e4e5a15ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8cb76a47-112b-44a7-85c9-c98d5ec24cd9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24bc1bc2-c9de-4a7f-a131-e8e1c239ed9c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c8b842c-7e7f-49ae-85c6-9c70b0103511</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0818c55e-1795-4892-b7b5-0ef743ad62fa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>738f3066-40a3-48ea-a898-c833350b7cd6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ECR/TestCases/TC_ECR_Meeting_Create_Reject</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce5d5086-b2eb-4995-9771-a7e949428e9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d87559d-c115-49d9-a418-ac0bdb1f43c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35c08d68-0ddc-4959-bbb8-975e7e53cd46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7d6bf52-4738-4205-b5d8-99253c590f48</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fdcb616-5eed-4d13-8fbb-dc19c3fce1bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d241e80-1fcb-41dc-b875-d4f0bd3fd106</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94d29568-f914-49e6-9c36-07fbab046e22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>001c0ed0-ccb5-4efd-b038-d214259a0140</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d466a6f4-6dd4-4c52-81d6-7fe2c70bf18d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4d1b331-f6e2-4a33-a818-ef1bbb461249</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89d0be2a-090e-4510-bcc2-a773884e9944</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49306b50-78be-4e01-aa72-aa414c255466</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75a8beda-e653-4eae-875c-9b041177f12b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14795d4b-8872-4cc4-96f3-a7ae46935a5e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
