<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Skills_pyWorkPage.ProfileDat</name>
   <tag></tag>
   <elementGuidId>07571fc7-dc11-471d-97ff-b72497b4d4fa</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PEGA_GRID4&quot;)/div[@id=&quot;PEGA_GRID_SKIN&quot;]/div[@id=&quot;RULE_KEY&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;dataValueWrite&quot;]/nobr[1]/span[1]/a[@class=&quot;iconInsert&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>pd(event);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;runActivity&quot;, [&quot;SetInsertSkillFlag&quot;, &quot;=&quot;, &quot;pyWorkPage.ProfileData.SkillGroup(1)&quot;, &quot;:event&quot;, &quot;&quot;]],[&quot;doGridAction&quot;,[&quot;:event&quot;,&quot;INSERTAFTER&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;CategoryForNewRow&quot;, &quot;&amp;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,&quot;pyWorkPage.ProfileData.SkillGroup(1)&quot;]]]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Skills_pyWorkPage.ProfileData.SkillGroup(1)_141</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>Icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add a row </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iconInsert</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20150929051200083634830</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dummy/Page_The Consulting Portal (TCP)/iframe_PegaGadget1Ifr</value>
   </webElementProperties>
</WebElementEntity>
