<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_PegaGadget1Ifr</name>
   <tag></tag>
   <elementGuidId>d3fb290a-8b4b-4f21-8af9-f35f5b376b78</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PegaGadget1Ifr&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/tcpqa/PRServlet/yHepcpv0oSmliMMZ2vftcv9nXVuQs0dE*/!TABTHREAD1?pyActivity=%40baseclass.doUIAction&amp;action=openWorkByHandle&amp;key=GS-OPS-DELTA-WORK-CONSULTANTPROFILE%20CPRO-ellia-1&amp;contentID=0e03e8da-c92a-4139-bd5e-fbbc1e8c2b6e&amp;dynamicContainerID=ea116240-74c5-4e95-b65b-4856fb4df9a1&amp;tabIndex=2&amp;prevContentID=11a003a8-8c90-4403-8bad-21d52c7b04fc&amp;prevRecordkey=Data-Portal%7CCOEDashboard%7Cundefined&amp;portalThreadName=STANDARD&amp;portalName=COEUserPortal7&amp;pzHarnessID=HID438E4B3B3A59D7746D6A30119F626226</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PegaGadget1Ifr</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PegaGadget1Ifr</value>
   </webElementProperties>
</WebElementEntity>
