<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AssignmentStatus</name>
   <tag></tag>
   <elementGuidId>4e2d2b99-e3f4-440f-855e-2c9b00a2f240</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@data-test-id='20150313133904023045379']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@data-test-id='20150313133904023045379']</value>
   </webElementProperties>
</WebElementEntity>
