<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CLOSE_WORK_OBJECT</name>
   <tag></tag>
   <elementGuidId>76cc1c78-9587-4a11-a7c3-e658d122079a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@data-test-id='201611040217330886176874']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@data-test-id='201611040217330886176874']</value>
   </webElementProperties>
</WebElementEntity>
