<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gapDrivenMethodology</name>
   <tag></tag>
   <elementGuidId>d8af4bcb-e177-47f5-abed-d81f624369e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[contains(@for,'GapDrivenImplementationMethodologyNo')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[contains(@for,'GapDrivenImplementationMethodologyNo')]</value>
   </webElementProperties>
</WebElementEntity>
