<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BSW_TEXT</name>
   <tag></tag>
   <elementGuidId>dfb4829c-c295-4e6a-817b-7ace6e0dc0ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@data-test-id='20161202044939039137413']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[@data-test-id='20161202044939039137413']</value>
   </webElementProperties>
</WebElementEntity>
