<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CLINIC_OUTCOME</name>
   <tag></tag>
   <elementGuidId>19e791c2-cf8d-469e-bf66-5b84dff49a8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[@for='ClinicMeetingActionApproved']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[@for='ClinicMeetingActionApproved']</value>
   </webElementProperties>
</WebElementEntity>
