<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>isCloudInitiativeYes</name>
   <tag></tag>
   <elementGuidId>51172a8f-1650-4447-8f3b-124706a8e71f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[@for='IsCloudInitiativeNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[@for='IsCloudInitiativeNo']</value>
   </webElementProperties>
</WebElementEntity>
