<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search</name>
   <tag></tag>
   <elementGuidId>2e852b8a-197c-44f4-8a71-5e07e17a85ef</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pySearchText&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyDisplayHarness$ppySearchText</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;TextInput&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pySearchText</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-keydown</name>
      <type>Main</type>
      <value>[[&quot;runActivity&quot;, [&quot;pyWorkIDSearch&quot;, &quot;pySearchString=#~pyDisplayHarness.pySearchText~#&amp;pySearchOnProperty=pyID&amp;pySearchMethod=exact&amp;pyReportClassName=Work-&amp;pyReportName=pyWorkIDSearch&quot;, &quot;pyDisplayHarness&quot;, &quot;:event&quot;, &quot;&quot;],,&quot;enter&quot;],[&quot;setValue&quot;, [[&quot;pyDisplayHarness.pySkipOpenWorkItem&quot;, &quot;&quot;, &quot;pyDisplayHarness.pyWorkIDSearchHandle&quot;, &quot;&quot;,&quot;#~pyDisplayHarness.pyWorkIDSearchHandle~#&quot;]],,&quot;enter&quot;],[&quot;openWorkByHandle&quot;,[&quot;#~pyDisplayHarness.pyWorkIDSearchHandle~#&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;false&quot;,&quot;&quot;],[&quot;&amp;&quot;,[&quot;OP&quot;,[&quot;$PpyDisplayHarness$ppySkipOpenWorkItem&quot;,&quot;!=&quot;,&quot;true&quot;,&quot;true&quot;]],[&quot;OP&quot;,[&quot;$PpyDisplayHarness$ppySkipOpenWorkItem&quot;,&quot;!=&quot;,&quot;&quot;,&quot;false&quot;]]],&quot;enter&quot;],[&quot;runScript&quot;, [&quot;closeSearchPopOver(event)&quot;],[&quot;&amp;&quot;,[&quot;OP&quot;,[&quot;$PpyDisplayHarness$ppySkipOpenWorkItem&quot;,&quot;!=&quot;,&quot;true&quot;,&quot;true&quot;]],[&quot;OP&quot;,[&quot;$PpyDisplayHarness$ppySkipOpenWorkItem&quot;,&quot;!=&quot;,&quot;&quot;,&quot;false&quot;]]],&quot;enter&quot;],[&quot;processAction&quot;, [&quot;pyWorkSearch&quot;,&quot;overlay&quot;,&quot;:event&quot;,&quot;&quot;,&quot;Rule-HTML-Section&quot;,&quot;&quot;,&quot;&quot;,&quot;anim-bottom&quot;,&quot;anim-bottom&quot;,&quot;Data-Portal&quot;,&quot;Data-Portal&quot;,&quot;false&quot;,&quot;false&quot;],[&quot;&amp;&quot;,[&quot;OP&quot;,[&quot;$PpyDisplayHarness$ppySkipOpenWorkItem&quot;,&quot;=&quot;,&quot;true&quot;,&quot;false&quot;]]],&quot;enter&quot;],[&quot;runDataTransform&quot;, [&quot;pyPopulateSearchString&quot;, &quot;=&quot;, &quot;pyDisplayHarness&quot;,&quot;:event&quot;],[&quot;&amp;&quot;,[&quot;OP&quot;,[&quot;$PpyDisplayHarness$ppySkipOpenWorkItem&quot;,&quot;=&quot;,&quot;true&quot;,&quot;false&quot;]]],&quot;enter&quot;]]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leftJustifyStyle</value>
   </webElementProperties>
</WebElementEntity>
