<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ECR_CHECKBOX</name>
   <tag></tag>
   <elementGuidId>b8629df6-2246-4dbc-a2af-75c1797dca43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@data-test-id='20160616095234061838865']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@data-test-id='20160616095234061838865']</value>
   </webElementProperties>
</WebElementEntity>
