<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Estimate</name>
   <tag></tag>
   <elementGuidId>48752177-d957-4378-be02-ba2a227da6e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='$PpyNavigation1513274116184$ppyElements$l1']/li[3]/a/span/span</value>
   </webElementProperties>
</WebElementEntity>
