<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>import</name>
   <tag></tag>
   <elementGuidId>e31bf5c6-705c-4b95-8438-3fe4576461d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@name='EngagementInfoSection_pyWorkPage_344']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@name='EngagementInfoSection_pyWorkPage_344']</value>
   </webElementProperties>
</WebElementEntity>
