<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MorethanOneRLSNO</name>
   <tag></tag>
   <elementGuidId>69890b35-be39-42b9-81a8-7d6ace43fbf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[@for='ShowOrHidePH1Flagfalse']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[@for='ShowOrHidePH1Flagfalse']</value>
   </webElementProperties>
</WebElementEntity>
