<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WOTAB</name>
   <tag></tag>
   <elementGuidId>ed4c8e62-2d2f-41c2-a270-7be542dcc91a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='RULE_KEY']/tbody/tr/td[2]/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='RULE_KEY']/tbody/tr/td[2]/span/label</value>
   </webElementProperties>
</WebElementEntity>
