<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>APPROVE_BUTTON</name>
   <tag></tag>
   <elementGuidId>a40a24cb-23db-438d-b914-7a8ab9f095bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[@for='ClinicDocApprovalActionApprove']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[@for='ClinicDocApprovalActionApprove']</value>
   </webElementProperties>
</WebElementEntity>
